#
# Copyright 2020 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#

FLEXSPI_DRIVERS_PATH	:=  ${PLAT_DRIVERS_PATH}/flexspi

PLAT_XSPI_INCLUDES	+= -I$(FLEXSPI_DRIVERS_PATH)/nor

XSPI_BOOT_SOURCES	+= $(FLEXSPI_DRIVERS_PATH)/nor/flexspi_nor.c
